name: .NET Core Desktop

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.7.2

    - name: Restore NuGet Packages
      run: nuget restore IK Admin Tool.sln

    - name: Build
      run: msbuild /p:Configuration=Release IK Admin Tool.sln

    - name: Test
      run: msbuild /t:IK Admin Tool.sln
